<a href="https://colab.research.google.com/github/tnjess/mdst_onboarding_checkpoints/blob/main/checkpoint0.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Checkpoint 0
## Do not remove comments that start with: "# @@@" (Those are question tags)

These exercises are a mix of Python and Pandas practice. Most should be no more than a few lines of code!

Do not remove comments that start with: "# @@@" (Those are question tags)

In [3]:
# @@@ Question 1: Here is a python list, initialize another list called b with the same values as a.
a = [1, 2, 3, 4, 5, 6]
b = [1, 2, 3, 4, 5, 6]

In [4]:
# @@@ Question 2: get a list containing the last 3 elements of b
# Yes, you can just type out [4, 5, 6] but we really want to see you demonstrate you know how to use list slicing in Python
b_subset = b[3:]
print(b_subset)

[4, 5, 6]

In [7]:
# @@@ Question 3: Create a list of numbers from 1 to 20
c = list(range(1, 21))
print(c)

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20]

In [13]:
# @@@ Question 4: now get a list with only the even numbers between 1 and 100
d = list(range(1, 101))
d_subset = d[1::2]
print(d_subset)

[2, 4, 6, 8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66, 68, 70, 72, 74, 76, 78, 80, 82, 84, 86, 88, 90, 92, 94, 96, 98, 100]

In [14]:
# @@@ Question 5: write a function that takes two numbers as arguments
# and returns the first number divided by the second
def divide(a, b):
  return a/b

result = divide(4,2)
print(result)

2.0

In [17]:
# @@@ Queston 6: fizzbuzz
# you will need to use both iteration and control flow
# go through all numbers from 1 to 30 in order
# if the number is a multiple of 3, print fizz
# if the number is a multiple of 5, print buzz
# if the number is a multiple of 3 and 5, print fizzbuzz and NOTHING ELSE
# if the number is neither a multiple of 3 nor a multiple of 5, print the number

for i in range(1, 31):
  if ((i % 3 == 0) & (i % 5 ==0)):
    print("fizzbuzz")
  elif (i % 3 == 0):
    print("fizz")
  elif (i % 5 == 0):
    print ("buzz")
  else:
    print(i)

1
2
fizz
4
buzz
fizz
7
8
fizz
buzz
11
fizz
13
14
fizzbuzz
16
17
fizz
19
buzz
fizz
22
23
fizz
buzz
26
fizz
28
29
fizzbuzz

In [19]:
# @@@ Question 7: create a dictionary that reflects the following menu pricing (taken from Ahmo's)
# Gyro: $9
# Burger: $9
# Greek Salad: $8
# Philly Steak: $10
menu = {"Gyro":"$9", "Burger":"$9", "Greek Salad":"$8", "Philly Steak": "$10"}
print(menu)

{'Gyro': '$9', 'Burger': '$9', 'Greek Salad': '$8', 'Philly Steak': '$10'}

In [35]:
# @@@ Question 8: load in the "starbucks.csv" dataset
# refer to how we read the cereal.csv dataset in the tutorial
import pandas as pd
df = pd.read_csv('/starbucks.csv')
df

,beverage_category,beverage,beverage_prep,calories,total fat,trans fat,saturated fat,sodium,total carbohydrates,cholesterol,dietary fibre,sugars,protein,vitamin a,vitamin c,calcium,iron,caffeine
0,coffee,brewed coffee,Short,3,0.1,0.0,0.0,0,5,0,0,0,0.3,0,0,0,0.0,175.0
1,coffee,brewed coffee,Tall,4,0.1,0.0,0.0,0,10,0,0,0,0.5,0,0,0,0.0,260.0
2,coffee,brewed coffee,Grande,5,0.1,0.0,0.0,0,10,0,0,0,1.0,0,0,0,0.0,330.0
3,coffee,brewed coffee,Venti,5,0.1,0.0,0.0,0,10,0,0,0,1.0,0,0,2,0.0,410.0
4,classic espresso drinks,caff latte,Short Nonfat Milk,70,0.1,0.1,0.0,5,75,10,0,9,6.0,10,0,20,0.0,75.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
237,frappuccino blended crme,strawberries crme (without whipped cream),Soymilk,320,3.2,0.4,0.0,0,250,67,1,64,5.0,6,8,20,10.0,0.0
238,frappuccino blended crme,vanilla bean (without whipped cream),Tall Nonfat Milk,170,0.1,0.1,0.0,0,160,39,0,38,4.0,6,0,10,0.0,0.0
239,frappuccino blended crme,vanilla bean (without whipped cream),Whole Milk,200,3.5,2.0,0.1,10,160,39,0,38,3.0,6,0,10,0.0,0.0
240,frappuccino blended crme,vanilla bean (without whipped cream),Soymilk,180,1.5,0.2,0.0,0,160,37,1,35,3.0,4,0,10,6.0,0.0
241,frappuccino blended crme,vanilla bean (without whipped cream),Grande Nonfat Milk,240,0.1,0.1,0.0,5,230,56,0,55,5.0,8,0,15,0.0,0.0

In [39]:
# @@@ Question 9: select all rows with more than and including 400 calories
df[df["calories"]>= 400]

,beverage_category,beverage,beverage_prep,calories,total fat,trans fat,saturated fat,sodium,total carbohydrates,cholesterol,dietary fibre,sugars,protein,vitamin a,vitamin c,calcium,iron,caffeine
81,signature espresso drinks,white chocolate mocha (without whipped cream),2% Milk,400,11.0,7.0,0.2,25,250,61,0,58,15.0,15,2,45,0.0,150.0
83,signature espresso drinks,white chocolate mocha (without whipped cream),Venti Nonfat Milk,450,7.0,6.0,0.0,10,310,78,0,74,19.0,25,2,60,2.0,150.0
84,signature espresso drinks,white chocolate mocha (without whipped cream),2% Milk,510,15.0,9.0,0.2,35,330,77,0,74,19.0,20,4,60,2.0,150.0
85,signature espresso drinks,white chocolate mocha (without whipped cream),Soymilk,460,13.0,6.0,0.0,5,290,70,1,64,16.0,15,2,60,20.0,150.0
128,tazo tea drinks,tazo green tea latte,2% Milk,450,10.0,5.0,0.3,40,230,72,2,71,17.0,25,20,50,6.0,110.0
214,frappuccino blended coffee,java chip (without whipped cream),Venti Nonfat Milk,420,5.0,4.0,0.0,5,340,90,2,84,7.0,10,0,20,35.0,145.0
215,frappuccino blended coffee,java chip (without whipped cream),Whole Milk,460,10.0,7.0,0.2,15,340,90,2,84,7.0,6,0,15,35.0,145.0
216,frappuccino blended coffee,java chip (without whipped cream),Soymilk,430,8.0,4.5,0.0,0,330,88,3,80,6.0,6,0,20,40.0,145.0

In [41]:
# @@@ Question 10: select all rows whose vitamin c content is higher than the iron content
df[df["vitamin c"] > df["iron"]]

,beverage_category,beverage,beverage_prep,calories,total fat,trans fat,saturated fat,sodium,total carbohydrates,cholesterol,dietary fibre,sugars,protein,vitamin a,vitamin c,calcium,iron,caffeine
11,classic espresso drinks,caff latte,2% Milk,190,7.0,3.5,0.2,30,170,19,0,17,12.0,20,2,40,0.0,150.000000
14,classic espresso drinks,caff latte,2% Milk,240,9.0,4.5,0.3,35,220,24,0,22,16.0,25,2,50,0.0,150.000000
35,classic espresso drinks,vanilla latte (or other flavoured latte),2% Milk,250,6.0,3.5,0.2,25,150,37,0,35,12.0,20,2,35,0.0,150.000000
38,classic espresso drinks,vanilla latte (or other flavoured latte),2% Milk,320,9.0,4.5,0.3,35,200,46,0,44,15.0,25,2,45,0.0,150.000000
69,signature espresso drinks,caramel macchiato,2% Milk,240,7.0,3.5,0.2,25,150,34,0,32,10.0,15,2,30,0.0,150.000000
72,signature espresso drinks,caramel macchiato,2% Milk,300,8.0,4.5,0.2,35,180,43,0,40,13.0,20,2,40,0.0,150.000000
75,signature espresso drinks,white chocolate mocha (without whipped cream),2% Milk,200,6.0,3.5,0.1,15,125,31,0,29,7.0,8,2,25,0.0,75.000000
77,signature espresso drinks,white chocolate mocha (without whipped cream),Tall Nonfat Milk,270,4.5,3.5,0.0,5,190,47,0,45,12.0,15,2,35,0.0,75.000000
78,signature espresso drinks,white chocolate mocha (without whipped cream),2% Milk,310,9.0,6.0,0.1,20,200,46,0,44,11.0,15,2,35,0.0,75.000000
81,signature espresso drinks,white chocolate mocha (without whipped cream),2% Milk,400,11.0,7.0,0.2,25,250,61,0,58,15.0,15,2,45,0.0,150.000000
84,signature espresso drinks,white chocolate mocha (without whipped cream),2% Milk,510,15.0,9.0,0.2,35,330,77,0,74,19.0,20,4,60,2.0,150.000000
118,tazo tea drinks,tazo green tea latte,Short Nonfat Milk,130,0.2,0.1,0.0,5,85,26,0,25,7.0,10,4,20,2.0,25.000000
119,tazo tea drinks,tazo green tea latte,2% Milk,170,4.0,2.0,0.1,15,95,26,0,25,7.0,10,6,20,2.0,25.000000
121,tazo tea drinks,tazo green tea latte,Tall Nonfat Milk,210,0.4,0.2,0.0,5,125,42,1,41,11.0,20,10,35,4.0,55.000000
122,tazo tea drinks,tazo green tea latte,2% Milk,260,6.0,3.0,0.2,25,140,41,1,40,10.0,15,10,35,4.0,55.000000
124,tazo tea drinks,tazo green tea latte,Grande Nonfat Milk,290,0.5,0.2,0.0,10,160,57,1,56,14.0,25,15,45,4.0,80.000000
125,tazo tea drinks,tazo green tea latte,2% Milk,350,8.0,4.0,0.2,30,180,57,1,55,14.0,20,15,45,4.0,80.000000
127,tazo tea drinks,tazo green tea latte,Venti Nonfat Milk,370,0.5,0.3,0.0,10,200,73,2,71,18.0,30,20,60,6.0,110.000000
128,tazo tea drinks,tazo green tea latte,2% Milk,450,10.0,5.0,0.3,40,230,72,2,71,17.0,25,20,50,6.0,110.000000
169,shaken iced beverages,shaken iced tazo tea lemonade (with classic sy...,Tall,100,0.0,0.0,0.0,0,0,25,0,24,0.1,0,10,0,0.0,89.520548
170,shaken iced beverages,shaken iced tazo tea lemonade (with classic sy...,Grande,130,0.0,0.0,0.0,0,0,33,0,33,0.1,0,15,0,0.0,89.520548
171,shaken iced beverages,shaken iced tazo tea lemonade (with classic sy...,Venti,190,0.0,0.0,0.0,0,0,49,0,49,0.1,0,20,0,0.0,89.520548
172,smoothies,banana chocolate smoothie,Grande Nonfat Milk,280,2.5,1.5,0.0,5,150,53,7,34,20.0,10,15,20,0.0,89.520548
175,smoothies,orange mango banana smoothie,Grande Nonfat Milk,260,1.0,0.3,0.0,5,120,54,6,37,16.0,50,80,10,30.0,15.000000
176,smoothies,orange mango banana smoothie,2% Milk,270,1.5,0.5,0.0,5,125,53,6,37,16.0,50,80,10,6.0,0.000000
177,smoothies,orange mango banana smoothie,Soymilk,270,1.5,0.4,0.0,5,120,53,6,36,15.0,50,80,10,6.0,0.000000
178,smoothies,strawberry banana smoothie,Grande Nonfat Milk,290,1.0,0.3,0.0,5,125,58,7,41,16.0,4,100,10,8.0,0.000000
179,smoothies,strawberry banana smoothie,2% Milk,290,2.0,1.0,0.0,5,125,58,7,41,16.0,4,100,10,8.0,0.000000
180,smoothies,strawberry banana smoothie,Soymilk,290,2.0,0.4,0.0,5,120,58,8,40,16.0,2,100,10,8.0,0.000000
229,frappuccino blended crme,strawberries crme (without whipped cream),Tall Nonfat Milk,170,0.1,0.1,0.0,0,140,39,0,38,3.0,6,6,10,2.0,0.000000
230,frappuccino blended crme,strawberries crme (without whipped cream),Whole Milk,190,3.0,1.5,0.1,10,140,38,0,37,3.0,4,6,10,2.0,0.000000
232,frappuccino blended crme,strawberries crme (without whipped cream),Grande Nonfat Milk,230,0.2,0.1,0.0,0,190,53,0,52,4.0,8,6,15,4.0,0.000000
233,frappuccino blended crme,strawberries crme (without whipped cream),Whole Milk,260,4.0,2.0,0.1,10,190,53,0,52,4.0,6,6,15,4.0,0.000000
235,frappuccino blended crme,strawberries crme (without whipped cream),Venti Nonfat Milk,310,0.2,0.1,0.0,5,260,70,0,69,6.0,10,8,20,4.0,0.000000
236,frappuccino blended crme,strawberries crme (without whipped cream),Whole Milk,350,6.0,3.0,0.2,15,260,70,0,68,6.0,8,8,20,4.0,0.000000

In [42]:
# @@@ Question 11: create a new column containing the caffeine per calories of each drink
df["caffeine per calories"] = df["caffeine"] / df["calories"]
df.head()

,beverage_category,beverage,beverage_prep,calories,total fat,trans fat,saturated fat,sodium,total carbohydrates,cholesterol,dietary fibre,sugars,protein,vitamin a,vitamin c,calcium,iron,caffeine,caffeine per calories
0,coffee,brewed coffee,Short,3,0.1,0.0,0.0,0,5,0,0,0,0.3,0,0,0,0.0,175.0,58.333333
1,coffee,brewed coffee,Tall,4,0.1,0.0,0.0,0,10,0,0,0,0.5,0,0,0,0.0,260.0,65.000000
2,coffee,brewed coffee,Grande,5,0.1,0.0,0.0,0,10,0,0,0,1.0,0,0,0,0.0,330.0,66.000000
3,coffee,brewed coffee,Venti,5,0.1,0.0,0.0,0,10,0,0,0,1.0,0,0,2,0.0,410.0,82.000000
4,classic espresso drinks,caff latte,Short Nonfat Milk,70,0.1,0.1,0.0,5,75,10,0,9,6.0,10,0,20,0.0,75.0,1.071429

In [43]:
# @@@ Question 12: what is the average calorie across all items?
df["calories"].mean()

np.float64(193.87190082644628)

In [45]:
# @@@ Question 13: how many different categories of beverages are there?
df["beverage_category"].nunique()

9

In [46]:
# @@@ Question 14: what is the average # calories for each beverage category?
bev_cats = df.groupby("beverage_category")
bev_cats["calories"].mean()

beverage_category
classic espresso drinks             140.172414
coffee                                4.250000
frappuccino blended coffee          276.944444
frappuccino blended crme            233.076923
frappuccino light blended coffee    162.500000
shaken iced beverages               114.444444
signature espresso drinks           250.000000
smoothies                           282.222222
tazo tea drinks                     177.307692
Name: calories, dtype: float64